### ISSUE TITLE
Add total balance charts

### ISSUE THREAD

**Issue by cryptoeax** [opencryptotrader/arbbot#20]
I suggest adding a total balance chart that overlays the individual exchange balances which helps show the gradual growth across exchanges.  Here is a screenshot of how this would look like:

![Total balance charts](https://screenshots.firefoxusercontent.com/images/20f11c19-10cd-4f4c-aa3e-99bc9ff27bf0.png)

I would submit a PR but rebasing this on top of master is almost impossible.  I'll have to wait for some of my other PRs to get merged first.  :-)

**Comment by jjc6676** [comment]
Is there anyway you can fork this and merge your fixes and additions? Not sure if the owner of this has been around.

**Comment by jjc6676** [comment]
Or what is the best way to pull down all of your updates to my folder?

**Comment by cryptoeax** [comment]
The author has merged my first PR (#1) so I'll wait for a few days.  People sometimes have engagements in real life that prevent them from being responsive on github at all times.  :-)  Plus I don't want to end up maintaining this project, since I will soon not have a ton of free time to work on it...

But for now I pushed most of the changes that I am running on my own bot to [this branch](https://github.com/cryptoeax/arbbot/tree/production).  Please note that I am experimenting with these patches so please review them before using them and use them at your own risk, etc.  :-)

**Comment by jjc6676** [comment]
Very much understandable and appreciated. Thank you for your time. Does your Branch have this Total Balance chart implemented?

**Comment by cryptoeax** [comment]
Yes.  It also has daily P&L charts implemented (I just pushed it.)  :-)  I will continue to push the changes that I keep implementing to it if you want to check it out.

Note that I use `git push -f` to push to this branch and do regular local rebases when doing local development on the bot, so I suggest not using `git pull` when fetching changes from it.  Instead it would be better to `git fetch` from my remote and occasionally `git reset --hard` a local branch to point to its latest changes on the `production` branch.

**Comment by jjc6676** [comment]
So can I just download the zip from your production branch and have all the changes made there?

Sorry, as I am still new to GIT





Sent from Mail for Windows 10

**Comment by jjc6676** [comment]
So can I just download the zip from your production branch and have all the changes made there?

Sorry, as I am still new to GIT

**Comment by cryptoeax** [comment]
> So can I just download the zip from your production branch and have all the changes made there?

Yes, you can periodically download https://github.com/cryptoeax/arbbot/archive/production.zip.  But then you have to replace the contents of your existing installation folder with the new one, and potentially deal with files that have been added/deleted/renamed/etc., so if you want to stick to downloading ZIP archives, it may be better to periodically do the following:

  * Stop the bot.
  * Backup your config.ini and config.inc.php.
  * Remove the previous installation directory.
  * Download the [ZIP package](https://github.com/cryptoeax/arbbot/archive/production.zip) again and extract it.  Move your config files in their old place again.
  * Restart the bot.

> Sorry, as I am still new to GIT

No worries!

**Comment by jjc6676** [comment]
These additions are very nice!

Got everything up and running now. 
My graph show nothing once unzipped, it is blank.

When I change it to graphMode = 1 then I see the PLNX and BTTRX exchanges though.

Is this how yours looks?

            var graphMode = "1";
            var graphExchange = "0";
            var graphCoin = "BTC";

            var stats = null;
            var totalPL = null;
            var profitableTrades = null;
            var plMode = "details";




Sent from Mail for Windows 10

**Comment by cryptoeax** [comment]
You should not need to change the source code.  Is your bot up and running and making trades?  If not, it is expected for the graphs to be blank.  If your bot is running successfully and the charts are still blank, I'd be curious to look at a screenshot of your UI, do you mind taking one in that case please? (I use Firefox which now comes with a built-in tool to take full-page screenshots which is quite handy for this purpose.)

The change that you made to set `graphMode` to 1 switches the graph to display the exchange rate of an altcoin as the bot has observed in the past.  For example see this screenshot from my bot:

![screenshot of comparative rates of FLO](https://screenshots.firefoxusercontent.com/images/1169212a-7ee7-4683-b537-6e8ede591079.png)

You can get this graph without needing to edit the code by clicking on the three links under the name of each altcoin in the Wallets section.  I have added tooltips to these links which explain what they are, which you can see by holding the mouse pointer over them.  The FLO chart in the screenshot above comes from clicking on the "T" link (comparative rate across the exchanges.)

**Comment by jjc6676** [comment]
Ok - I am thinking it may be something I did from the beginning then.

Does the folder need to be extracted to /var/www?
Can I unzip the contents of arbbot-production and work on it from the
desktop instead?

I can point nginx file to the correct location of the index.html in the
default file, but are there other underlying changes that need to be made?

I am thinking that may be the case for me, or my DB is having issues and I
need to rebuild a new UBUNTU VM and start over.

**Comment by jjc6676** [comment]
I am not home right now but I will screenshot my ui for you.
The bot is up and making trades currently.

**Comment by cryptoeax** [comment]
OK if the bot is running then you need to point a web server capable of running PHP scripts to the `web` subdirectory of the extracted archive.  (Just opening the index.html file in your browser from your hard disk won't work!).  It doesn't really matter if you use Apache or nginx.  I am using nginx with a cert that I got from LetsEncrypt (so that I can access the web UI over https) and have password protected the directory.

You need to add a `config.inc.php` to the `web` subdirectory [like this](https://github.com/opencryptotrader/arbbot/blob/master/web/config.inc.php.example).

**Comment by cryptoeax** [comment]
And if you have ideas for other useful features please file issues.

**Comment by jjc6676** [comment]
Ok here is my screenshot


It is pulling in most of the data except the chart, at least correctly.










Sent from Mail for Windows 10

**Comment by jjc6676** [comment]
Ok here is my screenshot


It is pulling in most of the data except the chart, at least correctly.


![capture](https://user-images.githubusercontent.com/4475063/33508823-688c4d22-d6c2-11e7-86e4-7e0db12685a2.PNG)

**Comment by jjc6676** [comment]
So I rebuilt it from scratch and now this haha...maybe I should just quit!

![capture](https://user-images.githubusercontent.com/4475063/33510054-3e88296e-d6cd-11e7-9bb1-a0cc8de6e245.PNG)

**Comment by jjc6676** [comment]
Rebuilt the WHOLE thing from scratch on a new VM.
Here is my new Screenshot.

![capture](https://user-images.githubusercontent.com/4475063/33510172-87582f30-d6ce-11e7-9c61-8ed14dfe977e.PNG)

**Comment by cryptoeax** [comment]
> Ok here is my screenshot
> It is pulling in most of the data except the chart, at least correctly.

OK, you are looking at the comparative rate chart.  I think you have edited the graphMode variable in the source code and have forgotten to switch it back to `"0"`.  ;-)  I suggest downloading a new clean copy of the code.  Please note that the only modifications you should be making to the extracted source code directory is adding the two config file, that's it!

> Also - none of the profits and losses are correct haha.

Yeah, I noticed a bug earlier today in #27.  I suspect the ~1416 POT sale in your screenshot suffers from the same problem.  Essentially the bot right now makes a guess!  But my `production` branch right now includes the fix for this in #28.  Unfortunately there is no way fix this for the existing database but to do it manually but upgrading your bot will help it calculate the P&L more accurately in the future.

**Comment by cryptoeax** [comment]
FWIW I don't think starting with a new VM was really necessary, in case you prefer to keep running your old bot.

**Comment by jjc6676** [comment]
Well I recreated the VM to clean out the old database and everything from scratch.

The last screenshot was a new bot running and nothing modified besides the two files you stated.

I have no idea why my graph won’t work, as the graph mode matches what your production file of index.html file has.


Maybe it has to do with permissions… I am not so sure at this point and just kind of giving in.

I appreciate all of you assistance!


Sent from Mail for Windows 10

**Comment by cryptoeax** [comment]
Do you get any errors reported to the browser web console?

**Comment by jjc6676** [comment]
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.


This is the only thing that shows in the web console





Sent from Mail for Windows 10

**Comment by jjc6676** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://192.168.198.132/graph.php?coin=BTC&exchange=0&mode=0&_=1512229469483


jquery.min.js:4 
GET http://192.168.198.132/graph.php?coin=BTC&exchange=0&mode=0&_=1512229559483 500 (Internal Server Error)

**Comment by cryptoeax** [comment]
I see, I think that is caused by a bug that I had in my code.  Sorry, it has been a few years since I had written any PHP code, and my memory is a bit rusty.  :-)  I have pushed a fix to the production branch which I believe should fix the issue for you, please grab a new ZIP file and give it a go and let me know if it works for you.

Also if you update your bot I would be curious to know if you would see a change in the daily profitable trades with my latest changes.  Since yesterday, with the fix in #30, my bot has been running about 20% more efficiently...

**Comment by jjc6676** [comment]
Firefox tells me this 

> Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.


Chrome tell me this

>jquery.min.js:4 GET http://192.168.198.132/graph.php?coin=BTC&exchange=0&mode=0&_=1512245052679 500 (Internal Server Error)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
updateGraph @ (index):131
(anonymous) @ (index):827
fire @ jquery.min.js:1
fireWith @ jquery.min.js:1
ready @ jquery.min.js:1
DOMContentLoaded @ jquery.min.js:1

**Comment by cryptoeax** [comment]
> Firefox tells me this

OK, that error is benign, and safe to ignore!

>     Use of getPreventDefault() is deprecated. Use defaultPrevented instead.
> 
> Chrome tell me this
> 
>     jquery.min.js:4 GET http://192.168.198.132/graph.php?coin=BTC&exchange=0&mode=0&_=1512245052679 500 (Internal Server Error)

Yes, this is what Chrome sees about the error, but the real error happens on the server side, so the error message actually doesn't reveal anything about the bug.  I looked at `/var/log/nginx/error.log` on mown system and noticed error logs that would be hit by the code that graph.php runs when invoked with exchange=0 and mode=0, which is what the fix I referred to was supposed to fix.

Are these errors coming from an installation from a ZIP package downloaded after my latest comment?  If yes, I would be curious to see what's in your `/var/log/nginx/error.log` (if that's where that file is on your system, I use Ubuntu.)  Just running `tail` on it after refreshing the page in your browser should be enough.

>     send @ jquery.min.js:4
>     ajax @ jquery.min.js:4
>     updateGraph @ (index):131
>     (anonymous) @ (index):827
>     fire @ jquery.min.js:1
>     fireWith @ jquery.min.js:1
>     ready @ jquery.min.js:1
>     DOMContentLoaded @ jquery.min.js:1

(FWIW this is the stack trace of the error, which tells you how you got to the point where the error occurred, not all that helpful to us in this particular case...)

> For what it is worth also, clicking on any other coins seem to work on the graph.

Yes, that matches the symptoms of the bug I discovered, since it only occurs with mode=0 and exchange=0, which is the Total BTC Balance chart graph.

> I should note that my folder resides on the desktop and my server confi`g has been changed to reflect that such as

That is perfectly fine!

> Also - once we get this up and running brother, I would like to send you some BTC :-)

That is very kind of you!  I would happily accept any donations at `3QofTzwjKAW8c6KwFikEJdRt2xYHkbuqWd`.  :-)

**Comment by jjc6676** [comment]
Here are the last few lines in my error log

> Stack trace:
#0 /home/jason/arbbot-master/web/WebDB.php(133): WebDB::getTotalValue('3', 'AMP', '0')
#1 /home/jason/arbbot-master/web/graph.php(9): WebDB::getGraph('AMP', '3', '0')
#2 {main}
  thrown in /home/jason/arbbot-master/web/WebDB.php on line 153" while reading response header from upstream, client: 192.168.198.1, server: localhost, request: "GET /graph.php?coin=AMP&exchange=0&mode=0&_=1512247102849 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "192.168.198.132", referrer: "http://192.168.198.132/"
2017/12/02 12:38:26 [error] 5196#5196: *1819 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: database selection error: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'arbitrage.snapshot.balance' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /home/jason/arbbot-master/web/WebDB.php:153
Stack trace:
#0 /home/jason/arbbot-master/web/WebDB.php(133): WebDB::getTotalValue('3', 'AMP', '0')
#1 /home/jason/arbbot-master/web/graph.php(9): WebDB::getGraph('AMP', '3', '0')
#2 {main}
  thrown in /home/jason/arbbot-master/web/WebDB.php on line 153" while reading response header from upstream, client: 192.168.198.1, server: localhost, request: "GET /graph.php?coin=AMP&exchange=3&mode=0&_=1512247103795 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "192.168.198.132", referrer: "http://192.168.198.132/"
2017/12/02 12:38:26 [error] 5196#5196: *1819 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: database selection error: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'arbitrage.snapshot.balance' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /home/jason/arbbot-master/web/WebDB.php:153
Stack trace:
#0 /home/jason/arbbot-master/web/WebDB.php(133): WebDB::getTotalValue('1', 'AMP', '0')
#1 /home/jason/arbbot-master/web/graph.php(9): WebDB::getGraph('AMP', '1', '0')
#2 {main}
  thrown in /home/jason/arbbot-master/web/WebDB.php on line 153" while reading response header from upstream, client: 192.168.198.1, server: localhost, request: "GET /graph.php?coin=AMP&exchange=1&mode=0&_=1512247104173 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "192.168.198.132", referrer: "http://192.168.198.132/"
2017/12/02 12:38:31 [error] 5196#5196: *1819 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: database selection error: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'arbitrage.snapshot.balance' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /home/jason/arbbot-master/web/WebDB.php:153
Stack trace:
#0 /home/jason/arbbot-master/web/WebDB.php(133): WebDB::getTotalValue('3', 'BTC', '0')
#1 /home/jason/arbbot-master/web/graph.php(9): WebDB::getGraph('BTC', '3', '0')
#2 {main}
  thrown in /home/jason/arbbot-master/web/WebDB.php on line 153" while reading response header from upstream, client: 192.168.198.1, server: localhost, request: "GET /graph.php?coin=BTC&exchange=0&mode=0&_=1512247109141 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "192.168.198.132", referrer: "http://192.168.198.132/"

**Comment by cryptoeax** [comment]
Oh wow, that shows a totally unrelated bug!  Apparently your mysql config is more conservative than mine and isn't letting the query pass through.  I submitted a fix in #32 and pushed it to the production branch.  Can you please retry downloading the latest code?  Thanks!

**Comment by jjc6676** [comment]
WELL WELL WELL!
Looks like we are in business!

All of my graphs are working now!

Sending some BTC to 3QofTzwjKAW8c6KwFikEJdRt2xYHkbuqWd for all your help!

**Comment by jjc6676** [comment]
Sent you some BTC...who knows in a few years it could be like thousands worth of USD!

**Comment by cryptoeax** [comment]
Glad to hear it!  And thanks a lot for the BTC.  :-)

Another useful new addition is some filtering options for the P&L charts to allow you to keep an eye on how well things are running over time, I think.

Side note, I guess at this point I am running my own minifork of this project?

**Comment by jjc6676** [comment]
> Side note, I guess at this point I am running my own minifork of this project?

um...ya think!

**Comment by Scorpic1** [comment]
Division by zero in  /var/www/arbbot-master/web/webdb.php on line 482

**Comment by jjc6676** [comment]
I have noticed some coins have very long deposit times, and sometimes they are different on each exchange.

For example, EMC2 was 999 confirmations at one point and then 1200 at another point in time.
That could mean a 16 hour transfer time.

Needless to say I had to blacklist the coin in the config file, but is there a better way to uncover how long transfers take?

**Comment by cryptoeax** [comment]
> Division by zero in /var/www/arbbot-master/web/webdb.php on line 482

Thanks for the bug report, pushed a fix to my `production` branch.

**Comment by cryptoeax** [comment]
> I have noticed some coins have very long deposit times, and sometimes they are different on each exchange.
> 
> For example, EMC2 was 999 confirmations at one point and then 1200 at another point in time.
> That could mean a 16 hour transfer time.
> 
> Needless to say I had to blacklist the coin in the config file, but is there a better way to uncover how long transfers take?

Hmm, that is a very interesting observation, and it's a fantastic idea to make the bot smart enough to take this into account.  Thanks for bringing this up.  Since I have decided to basically fork this project for my own use for now, filed https://github.com/cryptoeax/arbbot/issues/1.

**Comment by Scorpic1** [comment]
Have other problem, not see Recent trades, Management, Xfers tables.
Maybe problem in PHP version and modules.

![2017-12-04_163530](https://user-images.githubusercontent.com/18716398/33555604-1c6c4256-d912-11e7-9139-4f5f6f08a136.jpg)

**Comment by jjc6676** [comment]
Those will be blank until trades are made.

**Comment by Scorpic1** [comment]
But bot make transfer BTTRX to PLNX, Xfers is emty.
![2017-12-04_170927](https://user-images.githubusercontent.com/18716398/33556793-34b4db8a-d916-11e7-97c3-23b8965e7930.jpg)

**Comment by jjc6676** [comment]
Check your error log at 
/var/log/nginx

See what is there and it may help up discover an issue with the webserver

**Comment by Scorpic1** [comment]
Not have error.
What PHP version need use. I am use PHP 7.0.22

**Comment by jjc6676** [comment]
I have the same

PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by cryptoeax** [comment]
@Scorpic1 please file an issue in my fork, I am going to stop contributing to this project, please see #31 as to why.
