### ISSUE TITLE
Date is incorrect

### ISSUE THREAD

**Issue by jjc6676** [opencryptotrader/arbbot#21]
The current date seems to be one month behind... not sure the reason for this at all

**Comment by cryptoeax** [comment]
Which date are you referring to?

**Comment by jjc6676** [comment]
The graph for Profits and Losses states that it is 2017-10-29.

Should it not be 

2017-11-29

**Comment by cryptoeax** [comment]
Ah right, thanks.  This is an off by one error.  Since that PR isn't merged yet, let's close the issue and I'll just fix the bug in the PR.
